---
title: "report"
author: "Marta Ilundain"
date: "17/3/2021"
output: pdf_document
params: 
  method: 'lda'
  trainpercent: 0.75
  randomseed: 1
---

```{r}
###########################################################################

library(devtools)
library(usethis)
library(ggplot2)

library(kaggler)
kaggler::kgl_auth(username="martailundain",key="55489399e4f868af9b80e535ef1ab841")

library(shiny)
library(shinythemes)
require(shinyjs)
require(summarytools)

winedata <- kgl_datasets_download(owner_dataset = "rajyellow46/wine-quality", 
                              fileName = "winequalityN.csv")

#Preprocess of the data

wine = na.omit(winedata)
wine$type = as.factor(wine$type)
wine[,7] = log(wine[,7])
colnames(wine)[7] <- "log_free.sulfur.dioxide"
wine[,8] = log(wine[,8])
colnames(wine)[8] <- "log_total.sulfur.dioxide"
```

```{r}
setupData <- function(trainpercent, randomseed)
{
  # To make computations reproducible.
  set.seed(randomseed)

  # Partition intro training and testing.
  spl = caret::createDataPartition(wine$type, p = trainpercent, list = FALSE)  # 80% for training
  
  wineTrain = wine[spl,]
  wineTest = wine[-spl,]
  invisible( list(training=wineTrain, testing=wineTest) )
}

generic.fit <- function(method, training, testing)
{
  
  fit <- train(type ~ ., data = training, method=method)
  OutOfSample  <- predict(fit, newdata=testing)
  confusion <- confusionMatrix(testing$type, OutOfSample, positive='white')
  
  invisible( list(fit=fit, confusion=confusion) )
}

# Setup data when the partition or the seed change and use a specified method.
responseRoutine <- function(method, trainpercent, randomseed)
{
  d <- setupData(trainpercent, randomseed)
  fit <- generic.fit(method, d$training, d$testing)
  invisible(fit)
}
```

```{r}
result = responseRoutine(params$method, params$trainpercent, params$randomseed)
```

#Fit of the model:

```{r}
result$fit
```

#Confusion matrix:

```{r}
result$confusion
```



